name: keep_account_web
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  syncfusion_flutter_charts: ^20.3.58
  intl: ^0.18.1
  flutter_localization: ^0.2.0
  device_info_plus: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
